<?php

return [
    'رشت'                => 'rasht',
    'تهران'              => 'tehran',
    'اصفهان'             => 'isfahan',
    'شیراز'              => 'shiraz',
    'تبریز'              => 'tabriz',
    'اهواز'              => 'ahvaz',
    'کرمان'              => 'kerman',
    'رفسنجان'            => 'rafsanjan',
    'سنندج'              => 'sanandaj',
    'حمیدان'             => 'hamadan',
    'اراک'               => 'arak',
    'سمنان'              => 'semnan',
    'گرگان'              => 'gorgan',
    'بوشهر'              => 'bushehr',
    'هرمزگان'            => 'hormozgan',
    'خوزستان'            => 'khuzestan',
    'لرستان'             => 'loristan',
    'کردستان'            => 'kurdistan',
    'چهارمحال و بختیاری' => 'chaharmahal-and-bakhtiari',
    'گلستان'             => 'golestan',
    'فارس'               => 'fars',
    'خراسان رضوی'        => 'khorasan-e-razavi',
    'خراسان شمالی'       => 'khorasan-e-shomali',
    'خراسان جنوبی'       => 'khorasan-e-jonubi',
    'آذربایجان شرقی'     => 'azarbayjan-e-sharqi',
    'آذربایجان غربی'     => 'azarbayjan-e-gharbi',
    'زنجان'              => 'zanjan',
    'البرز'              => 'alborz',
    'ایلام'               => 'ilam',
    'قزوین'              => 'ghazvin',
    'قم'                 => 'qom',
    'کرمانشاه'           => 'kermanshah',
    'مازندران'           => 'mazandaran',
    'مركزی'              => 'markazi',
    'سیستان و بلوچستان'  =>'sistan-and-baluchistan',
    'یزد'                => 'yazd',
    'گیلان'               => 'rasht',
    'اردبیل'             => 'ardabil',
    'بندرعباس'           => 'bandar-abbas',
];
